### ISSUE TITLE
API Error occurred: method_deprecated

### ISSUE THREAD

**Issue by elusive** [JackuB/mermaid-preview#5]
I added the app to my slack channel and am able to use the /mermaid command to open the dialog that prompts for the diagram syntax.  The sample from mermaid-preview.com fails as does the other simple diagram i tried.  So finally I have tried 
```mermaid
graph TD;
A---B
A---C
```

and it fails also.  No matter what i try i get:  
<img width="546" alt="image" src="https://github.com/JackuB/mermaid-preview/assets/66542/2240bd30-754f-4577-b2ba-32ec088ac467">

**Comment by elusive** [comment]
sorry I forgot that ```mermarid``` would render the diagram on GH.  the simplest syntax I tried and that I put in the description above (but that was rendered into a diagram) was 
graph TD;
A---B
A---C

**Comment by JackuB** [comment]
I couldn't replicate this exact error message, but I ran into an array of different API errors in the past few weeks.
After some investigation, it turns out the culprit was the fly.io. Maybe they changed something on their side or had load issues, but their shared CPU instances couldn't handle the Mermaid-CLI rendering 🤔 

I switched to their dedicated CPU instances and it seems resolved for now. I'm closing this issue - but please reopen it or start a new one if you run into a similar error 🙏
